#!/usr/bin/env python3
"""
RE coverage / burndown report for SW_RACER_RE.

Parses scripts/Ghidra/master_functions.h (generated by ExportFunctionList.py from
the Ghidra DB) and reports how close we are to 100% named functions, plus the
biggest remaining clusters of unnamed FUN_ to target next.

Usage (from repo root):
    python scripts/Ghidra/coverage_report.py
    python scripts/Ghidra/coverage_report.py --min-cluster 4   # only clusters >= N unnamed

NOTE: master_functions.h is a STATIC export. It only reflects the Ghidra DB as of
the last ExportFunctionList.py run at the machine - it lags open/unmerged PRs and
in-session DB renames. Regenerate it (at the GUI) for a fresh scoreboard.
"""
import re, os, sys, argparse

HERE = os.path.dirname(os.path.realpath(__file__))
DEFAULT_SRC = os.path.join(HERE, "master_functions.h")

addr_re = re.compile(r'ADDR_0x([0-9a-fA-F]+)')
name_re = re.compile(r'(\w+)\s*\(')               # first identifier before '('
unnamed_re = re.compile(r'^(FUN_[0-9a-fA-F]{6,}|thunk_FUN_[0-9a-fA-F]{6,})$')

def parse(path):
    entries = []  # (addr:int, name:str, unnamed:bool)
    pending_addr = None
    for line in open(path, encoding="ascii", errors="replace"):
        m = addr_re.search(line)
        if m:
            pending_addr = int(m.group(1), 16)
            continue
        if pending_addr is None:
            continue
        nm = name_re.search(line)
        if nm:
            name = nm.group(1)
            entries.append((pending_addr, name, bool(unnamed_re.match(name))))
        pending_addr = None
    entries.sort(key=lambda e: e[0])
    return entries

def cluster(entries, gap=0x1000):
    """Group unnamed entries into runs; bridge across named entries while the
    address gap to the next unnamed stays under `gap`. Returns clusters with a
    'hint' = the nearest preceding NAMED function (subsystem guess)."""
    clusters = []
    cur = None
    last_named = None
    for addr, name, unnamed in entries:
        if not unnamed:
            last_named = name
            if cur and addr - cur["end"] >= gap:
                clusters.append(cur); cur = None
            continue
        if cur is None:
            cur = {"start": addr, "end": addr, "count": 1, "hint": last_named}
        elif addr - cur["end"] < gap:
            cur["end"] = addr; cur["count"] += 1
        else:
            clusters.append(cur)
            cur = {"start": addr, "end": addr, "count": 1, "hint": last_named}
    if cur:
        clusters.append(cur)
    return clusters

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=DEFAULT_SRC)
    ap.add_argument("--min-cluster", type=int, default=3)
    ap.add_argument("--gap", type=lambda x: int(x, 0), default=0x1000)
    ap.add_argument("--top", type=int, default=40)
    args = ap.parse_args()

    entries = parse(args.src)
    total = len(entries)
    unnamed = [e for e in entries if e[2]]
    nU = len(unnamed)
    nN = total - nU
    pct = 100.0 * nN / total if total else 0.0

    print(f"=== SW_RACER_RE function coverage ===")
    print(f"source: {os.path.relpath(args.src)}")
    print(f"total functions : {total}")
    print(f"named           : {nN}  ({pct:.1f}%)")
    print(f"unnamed (FUN_)  : {nU}  ({100-pct:.1f}%)")
    print()
    cl = cluster(entries, gap=args.gap)
    cl = [c for c in cl if c["count"] >= args.min_cluster]
    cl.sort(key=lambda c: c["count"], reverse=True)
    print(f"top unnamed clusters (>= {args.min_cluster}, gap < {hex(args.gap)}), by size:")
    print(f"  {'count':>5}  {'range':<23} {'near (subsystem hint)'}")
    for c in cl[:args.top]:
        rng = f"0x{c['start']:06x}-0x{c['end']:06x}"
        print(f"  {c['count']:>5}  {rng:<23} {c['hint'] or '(top of image)'}")
    shown = sum(c["count"] for c in cl[:args.top])
    print(f"\n  ({len(cl)} clusters >= {args.min_cluster}; "
          f"{shown} of {nU} unnamed shown in top {args.top})")

if __name__ == "__main__":
    main()
